from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
c = canvas.Canvas('..\\frontend\\sample_valid.pdf', pagesize=letter)
c.setFont('Helvetica', 12)
c.drawString(72, 720, 'This is a valid test PDF generated for the Document Summary Assistant.')
c.drawString(72, 700, 'It contains several sentences to allow extraction and summarization.')
c.drawString(72, 680, 'The quick brown fox jumps over the lazy dog.')
c.drawString(72, 660, 'This PDF is generated by reportlab in an automated test.')
c.save()
print('Wrote ../frontend/sample_valid.pdf')
