import React, { useState } from 'react';
import {
  Sparkles,
  Copy,
  Check,
  Download,
  FileDown,
  RotateCcw,
  Cpu,
  BarChart3,
  Clock,
  Percent,
} from 'lucide-react';
import { SummaryResultData } from '../types';
import KeyPoints from './KeyPoints';
import MainIdeas from './MainIdeas';

interface SummaryResultProps {
  data: SummaryResultData;
  documentName: string;
  onReset: () => void;
}

export default function SummaryResult({ data, documentName, onReset }: SummaryResultProps) {
  const [copied, setCopied] = useState(false);

  const handleCopySummary = () => {
    navigator.clipboard.writeText(data.summary);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadTxt = () => {
    const textContent = `DOCUMENT SUMMARY REPORT
Document: ${documentName}
Generated By: ${data.providerUsed}
Summary Mode: ${data.summaryLength.toUpperCase()}
==================================================

SUMMARY:
${data.summary}

KEY POINTS:
${data.keyPoints.map((kp, i) => `${i + 1}. ${kp}`).join('\n')}

MAIN IDEAS:
${data.mainIdeas.map((mi) => `- ${mi}`).join('\n')}

STATS:
- Original Words: ${data.stats?.originalWords ?? 'N/A'}
- Summary Words: ${data.stats?.summaryWords ?? 'N/A'}
- Compression: ${data.stats?.compressionRatio ?? 'N/A'}
`;

    const blob = new Blob([textContent], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `summary_${documentName.replace(/\.[^/.]+$/, '')}.txt`;
    link.click();
    URL.revokeObjectURL(url);
  };

  const handleDownloadMd = () => {
    const mdContent = `# Document Summary: ${documentName}

> **Provider:** ${data.providerUsed} | **Mode:** ${data.summaryLength.toUpperCase()}

---

## 📝 Summary
${data.summary}

---

## 🔑 Key Points
${data.keyPoints.map((kp) => `* ${kp}`).join('\n')}

---

## 💡 Main Ideas
${data.mainIdeas.map((mi) => `\`${mi}\``).join('  ')}

---

### 📊 Document Statistics
* **Original Words:** ${data.stats?.originalWords ?? 'N/A'}
* **Summary Words:** ${data.stats?.summaryWords ?? 'N/A'}
* **Compression Ratio:** ${data.stats?.compressionRatio ?? 'N/A'}
`;

    const blob = new Blob([mdContent], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `summary_${documentName.replace(/\.[^/.]+$/, '')}.md`;
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6 animate-fade-in">
      {/* Top Banner with Stats & Engine Used */}
      <div className="bg-gradient-to-r from-brand-900 via-indigo-950 to-slate-900 rounded-3xl p-6 text-white shadow-xl">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div className="space-y-1">
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full text-xs font-semibold bg-white/10 text-brand-200 border border-white/10 backdrop-blur-sm">
              <Sparkles className="w-3.5 h-3.5 text-amber-300 fill-amber-300" />
              <span>AI Summary Complete</span>
            </div>
            <h2 className="text-xl sm:text-2xl font-bold tracking-tight text-white">
              Document Analysis Results
            </h2>
            <p className="text-xs sm:text-sm text-slate-300">
              Source: <span className="text-white font-medium">{documentName}</span> • Mode:{' '}
              <span className="capitalize font-semibold text-brand-300">{data.summaryLength}</span>
            </p>
          </div>

          {/* Provider Badge */}
          <div className="flex items-center gap-2 self-start md:self-auto bg-white/10 backdrop-blur-md px-4 py-2 rounded-2xl border border-white/10 text-xs">
            <Cpu className="w-4 h-4 text-brand-300" />
            <div>
              <div className="text-[10px] uppercase tracking-wider text-slate-400 font-bold">Engine</div>
              <div className="font-semibold text-white">{data.providerUsed}</div>
            </div>
          </div>
        </div>

        {/* Analytics stats bar */}
        {data.stats && (
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 mt-6 pt-5 border-t border-white/10">
            <div className="bg-white/5 rounded-xl p-3 border border-white/5">
              <div className="flex items-center gap-1.5 text-xs text-slate-300">
                <BarChart3 className="w-3.5 h-3.5 text-brand-300" />
                <span>Original Words</span>
              </div>
              <div className="text-lg font-bold text-white mt-1">
                {data.stats.originalWords.toLocaleString()}
              </div>
            </div>

            <div className="bg-white/5 rounded-xl p-3 border border-white/5">
              <div className="flex items-center gap-1.5 text-xs text-slate-300">
                <Sparkles className="w-3.5 h-3.5 text-indigo-300" />
                <span>Summary Words</span>
              </div>
              <div className="text-lg font-bold text-white mt-1">
                {data.stats.summaryWords.toLocaleString()}
              </div>
            </div>

            <div className="bg-white/5 rounded-xl p-3 border border-white/5">
              <div className="flex items-center gap-1.5 text-xs text-slate-300">
                <Percent className="w-3.5 h-3.5 text-emerald-300" />
                <span>Compression</span>
              </div>
              <div className="text-lg font-bold text-emerald-400 mt-1">
                {data.stats.compressionRatio}
              </div>
            </div>

            <div className="bg-white/5 rounded-xl p-3 border border-white/5">
              <div className="flex items-center gap-1.5 text-xs text-slate-300">
                <Clock className="w-3.5 h-3.5 text-amber-300" />
                <span>Reading Time</span>
              </div>
              <div className="text-lg font-bold text-amber-300 mt-1">
                {data.stats.estimatedReadingTimeSummary}
              </div>
            </div>
          </div>
        )}
      </div>

      {/* Main Results Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Left Column (2 cols): Summary */}
        <div className="lg:col-span-2 space-y-6">
          <div className="bg-white rounded-3xl border border-slate-200/80 p-6 sm:p-8 shadow-sm flex flex-col justify-between">
            <div>
              <div className="flex items-center justify-between pb-4 border-b border-slate-100 mb-5">
                <div className="flex items-center space-x-2.5">
                  <div className="p-2 rounded-xl bg-brand-50 text-brand-600 border border-brand-100">
                    <Sparkles className="w-5 h-5" />
                  </div>
                  <div>
                    <h3 className="text-lg font-bold text-slate-900">Summary</h3>
                    <p className="text-xs text-slate-500">Natural-language synthesis</p>
                  </div>
                </div>

                <div className="flex items-center space-x-2">
                  <button
                    type="button"
                    onClick={handleCopySummary}
                    className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-xs font-semibold text-slate-700 bg-slate-100 hover:bg-slate-200 active:bg-slate-300 transition"
                    title="Copy summary to clipboard"
                  >
                    {copied ? (
                      <>
                        <Check className="w-3.5 h-3.5 text-emerald-600" />
                        <span className="text-emerald-700 font-bold">Copied</span>
                      </>
                    ) : (
                      <>
                        <Copy className="w-3.5 h-3.5 text-slate-500" />
                        <span>Copy Summary</span>
                      </>
                    )}
                  </button>
                </div>
              </div>

              {/* Summary Text */}
              <div className="text-sm sm:text-base text-slate-800 leading-relaxed font-normal whitespace-pre-wrap">
                {data.summary}
              </div>
            </div>

            {/* Export & Actions footer */}
            <div className="mt-8 pt-6 border-t border-slate-100 flex flex-wrap items-center justify-between gap-3">
              <div className="flex flex-wrap items-center gap-2">
                <button
                  type="button"
                  onClick={handleDownloadTxt}
                  className="inline-flex items-center gap-1.5 px-3.5 py-2 rounded-xl text-xs font-semibold text-slate-700 bg-white border border-slate-200 hover:bg-slate-50 active:bg-slate-100 shadow-xs transition"
                >
                  <Download className="w-3.5 h-3.5 text-slate-500" />
                  <span>Download .txt</span>
                </button>

                <button
                  type="button"
                  onClick={handleDownloadMd}
                  className="inline-flex items-center gap-1.5 px-3.5 py-2 rounded-xl text-xs font-semibold text-slate-700 bg-white border border-slate-200 hover:bg-slate-50 active:bg-slate-100 shadow-xs transition"
                >
                  <FileDown className="w-3.5 h-3.5 text-brand-600" />
                  <span>Download .md</span>
                </button>
              </div>

              <button
                type="button"
                onClick={onReset}
                className="inline-flex items-center gap-1.5 px-4 py-2 rounded-xl text-xs font-bold text-brand-700 bg-brand-50 hover:bg-brand-100 active:bg-brand-200 border border-brand-200/60 shadow-xs transition ml-auto"
              >
                <RotateCcw className="w-3.5 h-3.5" />
                <span>Upload Another Document</span>
              </button>
            </div>
          </div>
        </div>

        {/* Right Column (1 col): Key Points & Main Ideas */}
        <div className="space-y-6 flex flex-col">
          <div className="flex-1">
            <KeyPoints keyPoints={data.keyPoints} />
          </div>
          <div className="flex-1">
            <MainIdeas mainIdeas={data.mainIdeas} />
          </div>
        </div>
      </div>
    </div>
  );
}
